task_manager/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

task_manager/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    # index, create, update, delete
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('in-progress/<int:id>/', views.in_progress, name='in_progress'),
    path('completed/<int:id>/', views.completed, name='completed'),
    path('update/<int:id>/', views.update, name='update'),
    path('undo-progress/<int:id>/', views.undo_progress, name='undo_progress'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('reset_all', views.reset_all, name='reset_all'),
    path('new_category/', views.new_category, name='new_category'),
    path('clear_categories5364/', views.clear_categories, name='clear_categories'),
]

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'task_manager'
handler404 = 'core.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('reporting/', include('reporting.urls')),
    path('accounts/', include('accounts.urls')),    
]

task_manager/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Categories"
        
class Task(models.Model):
    title = models.CharField(max_length=255)
    in_progress = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    

    def __str__(self):
        return self.title + ' | ' + "Completed" if self.completed else "To do"

task_manager/dashboard/forms.py
from django import forms
from .models import Task, Category
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = False
        
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control rounded-md p-1 font-light text-[#9abad8] bg-[#0d1c2a] outline-none md:w-full',
                    'placeholder': 'Add a category..',
                }
            )
        }

class NewTaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = False
        
    class Meta:
        model = Task
        fields = ['title']
        
        placeholder = {
            'title': 'Add a task..',
        }
        
        
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control rounded-md p-1 font-light text-[#9abad8] bg-[#0d1c2a] outline-none w-[93%] md:w-full',
                    'placeholder': 'Add a task..',
                    }
                )
        }

task_manager/dashboard/views.py
from django.shortcuts import render, redirect
# user
from django.contrib.auth.models import User
from django.http import HttpResponseNotFound, HttpResponseServerError
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import Task, Category
from reporting.models import CompletedTask
from django.utils import timezone
import time
from .forms import CategoryForm, NewTaskForm

@login_required
def index(request):
    # todos in reverse order
    todos = Task.objects.filter(completed=False, in_progress=False, user=request.user).order_by('-created_at')
    completed = Task.objects.filter(completed=True, user=request.user).order_by('-completed_at').filter(completed_at__gte=timezone.now().replace(hour=0, minute=0, second=0, microsecond=0))
    in_progress = Task.objects.filter(in_progress=True, user=request.user)
    categories = Category.objects.filter(user=request.user)
    context = {
        "tasks_todo": todos,
        "tasks_completed": completed,
        "tasks_in_progress": in_progress,
        "categories": categories,
        "task_form": NewTaskForm(),
        "category_form": CategoryForm()
    }
    return render(request, 'dashboard/tasks_list.html', context)

@login_required
def in_progress(request, id):
    task = Task.objects.get(id=id, user=request.user)
    task.in_progress = not task.in_progress
    task.save()
    return redirect('dashboard:index')

@login_required
def undo_progress(request, id):
    task = Task.objects.get(id=id, user=request.user)
    task.in_progress = not task.in_progress
    task.save()
    return redirect('dashboard:index')

@login_required
def completed(request, id):
    try:
        task = Task.objects.get(id=id, user=request.user)
        task.completed = not task.completed
        task.completed_at = timezone.now()
        task.in_progress = False
        task.save()
        if task.completed:
            CompletedTask.objects.create(title=task.title, created_at=task.created_at, completed_at=task.completed_at, category=task.category.name, user=task.user)
        return redirect('dashboard:index')

    except Task.DoesNotExist:
        # Handle the case where the task does not exist
        return HttpResponseNotFound("Task not found.")

    except Exception as e:
        # Print or log the exception for debugging
        print(f"An error occurred: {e}")
        # Return an HTTP response with a meaningful error message
        return HttpResponseServerError("An error occurred while processing your request. Please try again later.")


@login_required
def create(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            # Create a new task
            task = form.save(commit=False)
            task.user = request.user
            task.category = Category.objects.get(id=request.POST.get('category'))
            task.save()
        
        return redirect('dashboard:index')
    else:
        form = NewTaskForm()
    return render(request, 'dashboard/create_task.html', {'task_form': form})

@login_required
def update(request, id):
    task = Task.objects.get(id=id, user=request.user)
    task.completed = not task.completed
    task.save()
    return render(request, 'dashboard/tasks_list.html')

@login_required
def delete(request, id):
    task = Task.objects.get(id=id, user=request.user)
    task.delete()
    return redirect('dashboard:index')

@login_required
def reset_all(request):
    Task.objects.filter(user=request.user).delete()
    return redirect('dashboard:index')

@login_required
def new_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
        return redirect('dashboard:index')
    else:
        form = CategoryForm()
    return render(request, 'dashboard/create_category.html', {'category_form': form})

@staff_member_required
def clear_categories(request):
    Category.objects.all().delete()
    return redirect('dashboard:index')

task_manager/dashboard/templates/dashboard/tasks_list.html
<style>
    .no-scrollbar::-webkit-scrollbar {
        display: none;
    }

    /* Hide scrollbar for IE, Edge, and Firefox */
    .no-scrollbar {
        -ms-overflow-style: none;
        /* IE and Edge */
        scrollbar-width: none;
        /* Firefox */
    }
</style>
{% include 'core/base.html' %}
{% block content %}
<div class="flex flex-col md:flex-row justify-around items-center space-x-3 bg-[#00040a] p-4 md:w-screen sticky top-0 z-49">
    <!--Welcome message to ask the user for tasks-->
    <div class="flex flex-col justify-center items-center space-y-2 text-[#b9d1e8]">
        <h1 class="text-2xl font-bold font-mono">Welcome, {{ user.username }}</h1>
        <p>What tasks do you have today?</p>
    </div>
    <!--Add task-->
    <div class="flex flex-col justify-start items-center space-x-2 sm:space-x-4 mt-5 px-2">
        <form action="{% url 'dashboard:create' %}" method="post" class="flex justify-center items-center space-x-2">
            {% csrf_token %}
            <div class="flex flex-row justify-center items-center space-x-2">
                {{ task_form.as_div }}
            <select name="category"
                class="rounded-md p-1 font-light text-[#9abad8] outline-none bg-[#0d1c2a] focus:bg-[#2f5170]" required id="category" onchange="this.style.color='#9abad8'" >
                <option value="" disabled selected>Select a Category</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
            <!--Submit button-->
            <button type="submit" name="task_form" class="bg-[#0d1c2a] text-[#9abad8] font-normal rounded-md p-1 hover:bg-green-700">
                <svg xmlns="http://www.w3.org/2000/svg"
                    class="h-6 w-6 fill-[#9abad8] hover:text-slate-100 transform hover:scale-110"
                    viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                    <path
                        d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z" />
                </svg>
            </button>
            <button type="reset" class="hidden md:block bg-[#0d1c2a] text-[#9abad8] font-normal rounded-md p-1 w-24">Reset</button>
            <a href="{% url 'dashboard:reset_all' %}"
                class="hidden md:block bg-[#0d1c2a] text-[#9abad8] font-normal rounded-md p-1 w-24 hover:bg-red-900 text-center">Reset
                All</a>
            </div>
        </form>
    </div>
    <!--New Category-->
    <div class="hidden md:flex justify-end items-center space-x-4 mt-5">
        <form action="{% url 'dashboard:new_category' %}" method="post" class="flex items-center space-x-2">
            {% csrf_token %}
            {{ category_form.as_div }}
            <button type="submit" name="category_form" class="bg-[#0d1c2a] text-[#9abad8] font-normal rounded-md p-1 hover:bg-green-700">
                <svg xmlns="http://www.w3.org/2000/svg"
                    class="h-6 w-6 fill-[#9abad8] hover:text-slate-100 transform hover:scale-110"
                    viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                    <path
                        d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z" />
                </svg>
            </button>
            <button type="reset" class="bg-[#0d1c2a] text-[#9abad8] font-normal rounded-md p-1 w-24">Reset</button>
        </form>
    </div>
</div>
<div class="container bg-inherit text-center text-2xl font-bold text-[#9abad8] mx-auto font-sans w-full">
    <div class="flex flex-row overflow-x-auto no-scrollbar space-x-4 mt-5 text-black font-normal px-3 w-full">
        <!--Card-->
        <div class="min-w-full md:min-w-[47vh] col-md-4 rounded-xl border-2 hover:border-[#555f6e61] border-[#4a546330] bg-[#1c212840] hover:bg-[#1c2128] group duration-300">
            <h2 class="my-2 md:mb-5 text-[#88bcce]">To Do's</h2>
            <div class="border-t-2 border-[#3b6674] w-[27vh] mx-auto"></div>
            <p class="text-lg text-slate-500 font-sans mt-2 mb-1">This task hasn't been started yet</p>
            <ul class="list-group h-[49vh] md:h-[60vh] overflow-y-auto px-4 no-scrollbar md:mb-4">
                {% for task in tasks_todo %}
                <li class="my-3 group/item">
                    <div class="relative border-1 border-[#3b6674] bg-[#2d333b40] text-[#9abad8] p-4 rounded-lg hover:bg-[#303a47]">
                        <!--Category-->
                        <div
                            class="border-t-[63px] border-t-[#204e5e] border-r-[72px] border-r-transparent absolute top-0 left-0 rounded-md">
                            <span
                                class="text-xs text-[#9abad8] font-mono font-light transform -rotate-45 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 pl-20 pb-9">
                                {{ task.category }}
                            </span>
                        </div>
                        <!--Task Title-->
                        <div class="pl-8">
                            <a href=" {% url 'dashboard:in_progress' task.id %}">{{ task.title }}</a>
                        </div>
                        <!--Delete Task-->
                        <a href="{% url 'dashboard:delete' task.id %}"
                            class="fill-[#9abad8] bg-transparent font-bold hover:cursor-pointer hover:block absolute top-3 right-0 p-2 h-full">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                class="hidden group-hover/item:block h-6 w-6 text-[#9abad8] hover:text-slate-100 transform hover:scale-110"
                                viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                                <path
                                    d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z" />
                            </svg>
                        </a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="min-w-full md:min-w-[47vh] col-md-4 rounded-xl border-2 hover:border-[#555f6e61] border-[#4a546330] bg-[#1c212840] hover:bg-[#1c2128] group duration-300">
            <h2 class="text-[#f9cb55] my-2 md:mb-5">In Progress</h2>
            <div class="border-t-2 border-[#9e7f31] w-[27vh] mx-auto"></div>
            <p class="text-lg text-slate-500 font-sans mt-2 mb-1">This task is currently in progress</p>
            <ul class="list-group h-[49vh] md:h-[60vh] overflow-y-auto px-4 no-scrollbar md:mb-4">
                {% for task in tasks_in_progress %}
                <li class="my-3 group/item">
                    <div class="relative border-1 border-[#3b6674] bg-[#2d333b40] text-[#9abad8] p-4 rounded-lg hover:bg-[#303a47]">
                        <!--Category-->
                        <div class="border-t-[63px] border-t-[#9a8550] border-r-[72px] border-r-transparent absolute top-0 left-0 rounded-md">
                            <span
                                class="text-xs text-[#f0ebdd] font-mono font-light transform -rotate-45 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 pl-20 pb-9">
                                {{ task.category }}
                            </span>
                        </div>
                        <div class="pl-8">
                            <!--Task Title-->
                            <a href=" {% url 'dashboard:completed' task.id %}">{{ task.title }}</a>
                        </div>
                        <!--Undo Progress-->
                        <a href="{% url 'dashboard:undo_progress' task.id %}"
                            class="fill-[#e2e1d0] bg-transparent font-bold group-hover:cursor-pointer group group-hover:block absolute top-3 right-0 p-2 h-full">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="hidden group-hover/item:block h-6 w-6 fill-[#e2e1d0] hover:text-slate-100 transform hover:scale-110"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path stroke-width="30" d="M75 75L41 41C25.9 25.9 0 36.6 0 57.9V168c0 13.3 10.7 24 24 24H134.1c21.4 0 32.1-25.9 17-41l-30.8-30.8C155 85.5 203 64 256 64c106 0 192 86 192 192s-86 192-192 192c-40.8 0-78.6-12.7-109.7-34.4c-14.5-10.1-34.4-6.6-44.6 7.9s-6.6 34.4 7.9 44.6C151.2 495 201.7 512 256 512c141.4 0 256-114.6 256-256S397.4 0 256 0C185.3 0 121.3 28.7 75 75zm181 53c-13.3 0-24 10.7-24 24V256c0 6.4 2.5 12.5 7 17l72 72c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-65-65V152c0-13.3-10.7-24-24-24z"/></svg>

                        </a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="min-w-full md:min-w-[47vh] col-md-4 rounded-xl border-2 hover:border-[#555f6e61] border-[#4a546330] bg-[#1c212840] hover:bg-[#1c2128] group duration-300">
            <h2 class="text-[#79c267] my-2 md:mb-5">Completed</h2>
            <div class="border-t-2 border-[#205e38] w-[27vh] mx-auto"></div>
            <p class="text-lg text-slate-500 font-sans mt-2 mb-1">This task has been completed today</p>
            <ul class="list-group h-[49vh] md:h-[60vh] overflow-y-auto px-4 no-scrollbar md:mb-4
            ">
                {% for task in tasks_completed %}
                <li class="my-3">
                    <div class="relative border-1 border-[#3b6674] bg-[#2d333b40] text-[#9abad8] p-4 rounded-lg hover:bg-[#303a47]">
                        <!--Category-->
                        <div class="border-t-[63px] border-t-[#205e38] border-r-[72px] border-r-transparent absolute top-0 left-0 rounded-md">
                            <span
                                class="text-xs text-[#d2f7e0] font-mono font-light transform -rotate-45 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 pl-20 pb-9">
                                {{ task.category }}</span>
                        </div>
                        <!--Task Title-->
                        <div class="pl-8">
                            <a>{{ task.title }}</a>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}
<script>
    const colorChange = document.getElementById('color-change');

    colorChange.addEventListener('mouseenter', () => {
        setTimeout(() => {
            colorChange.classList.remove('bg-blue-500');
            colorChange.classList.add('bg-green-500');
        }, 3000);

        setTimeout(() => {
            colorChange.classList.remove('bg-green-500');
            colorChange.classList.add('bg-red-500');
        }, 5000);
    });

    colorChange.addEventListener('mouseleave', () => {
        // Reset color on mouse leave
        colorChange.classList.remove('bg-green-500', 'bg-red-500');
    });
</script>