task_manager/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html',
        authentication_form=LoginForm,
    ), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

task_manager/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

task_manager/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    # index, create, update, delete
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('in-progress/<int:id>/', views.in_progress, name='in_progress'),
    path('completed/<int:id>/', views.completed, name='completed'),
    path('update/<int:id>/', views.update, name='update'),
    path('undo-progress/<int:id>/', views.undo_progress, name='undo_progress'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('reset_all', views.reset_all, name='reset_all'),
    path('new_category/', views.new_category, name='new_category'),
    path('clear_categories5364/', views.clear_categories, name='clear_categories'),
]

task_manager/reporting/urls.py
from django.urls import path
from . import views

app_name = 'reporting'

urlpatterns = [
    path('tasks_history/', views.tasks_history, name='tasks_history'),
    path('clear_history5364/', views.clear_history, name='clear_history'),
]

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'task_manager'
handler404 = 'core.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('reporting/', include('reporting.urls')),
    path('accounts/', include('accounts.urls')),    
]

task_manager/core/views.py
from django.shortcuts import render, redirect

def index(request):
    return redirect('dashboard:index')

def handler404(request, exception):
    return render(request, 'core/404.html', status=404)

task_manager/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Task Manager</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
</head>


<body class="bg-[#202c3e] md:w-full">
    <header
        class="lg:px-16 px-4 bg-[#0d1c2a] p-3 text-slate-100 flex flex-wrap items-center py-2 shadow-md sticky top-0 z-50">
        <div class="flex-1 flex justify-between items-center">
            <a href="{% url 'dashboard:index' %}" class="text-2xl font-bold font-mono">Task Manager</a>
        </div>
        <svg class="h-6 w-6 cursor-pointer md:hidden block"> </svg>
        <!-- Hamburger Icon -->
        <svg xmlns="<http://www.w3.org/2000/svg>" id="menu-button" class="h-6 w-6 cursor-pointer md:hidden block"
            fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>

        <div class="hidden w-full md:flex md:items-center md:w-auto" id="menu">
            <nav>
                <ul class="md:flex items-center justify-between text-slate-400 text-base md:pt-0">
                    <li><a class="md:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-[#2f5170] hover:text-slate-50"
                            href="{% url 'dashboard:index' %}">Dashboard</a></li>
                    <li><a class="md:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-[#2f5170] hover:text-slate-50"
                            href="{% url 'reporting:tasks_history' %}">History</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="md:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-red-600 hover:text-red-600"
                            href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="md:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-[#2f5170] hover:text-blue-500"
                            href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a class="md:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-[#2f5170] hover:text-green-500"
                            href="{% url 'accounts:signup' %}">Register</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    {% block content %}
    {% endblock %}
    <script>
        const button = document.querySelector('#menu-button'); // Hamburger Icon
        const menu = document.querySelector('#menu'); // Menu

        button.addEventListener('click', () => {
            menu.classList.toggle('hidden');
        });
    </script>
</body>

</html>

task_manager/core/templates/core/index.html
{% load static %}
{% include 'core/base.html' %}
{% block content %}
<p>
    Welcome to Task Manager
</p>
{% endblock %}